server:
  tomcat:
    max-threads: 1024
    max-connections: 10240
    accept-count: 100
  servlet:
    context-path: /
#    port: 443
#    ssl:
#        key-store: ssl/server.keystore
#        key-alias: tomcat
#        enabled: true
#        key-store-password: 123456
#        key-store-type: JKS


#本地一些配置信息
cobra:
  config:
    page-size: 20
  project:
    name: cobra.admin
    code: cobra.admin
    version: 1.0.0
  keys:
    tencent-map: xxx
    aliyun:
      accessKeyId-oss: xxx
      accessKeySecret-oss: xxx
      endpoint-oss: oss-cn-beijing.aliyuncs.com
      bucket-name-oss: xxx-oss


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      update-strategy: not_null
      insert-strategy: ignored
      logic-delete-value: 0
      logic-not-delete-value: 1
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  jackson:
    default-property-inclusion: non_null    #json中如果为空则不返回
    serialization:
      write-dates-as-timestamps: true #json中包含Date转成时间戳
  datasource:
    #配置监控统计拦截的filters,去掉后druid监控界面sql将无法统计
    filters: stat
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 3000
      pool-name: NextHikariCP
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  type: com.alibaba.druid.pool.DruidDataSource
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall,slf4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
